### ISSUE TITLE
[typo] 这不是一个 python 的包吗

### ISSUE THREAD

**Issue by NWYLZW** [mnixry/nonebot-plugin-filehost#1]
你已经变成 `nodejs` 的形状了，mix
（指 repo 的名字不是 snake case

**Comment by mnixry** [comment]
感谢您的提醒, 但是本仓库命名并没有问题

这是NoneBot2[官方推荐的命名方式](https://v2.nonebot.dev/advanced/publish-plugin.html)

> 发布时，请您为自己的插件取一个清晰易懂的名字。通常而言，一款 NoneBot2 插件名称使用 nonebot-plugin- 作为前缀(如nonebot-plugin-foo)，以 nonebot_plugin_ 作为导入名的前缀(如nonebot_plugin_foo)，这并非是强制规范, 而是为了防止与其他 PyPI 包产生冲突, 所以我们推荐您在没有特殊需求的情况下这样做。

以PyPI包名作为仓库名称是合情合理的习惯性用法, 简单搜索一下, 采用该命名方式的仓库包括:
- https://github.com/nonebot/plugin-localstore
- https://github.com/nonebot/adapter-telegram
- https://github.com/nonebot/plugin-apscheduler
- https://github.com/iyume/nonebot-plugin-arcaea
- https://github.com/rmuchan/nonebot-plugin-flexperm
- https://github.com/ffreemt/nonebot-plugin-guess-game

由于以上原因, 我将关闭该Issue, 如果您有任何进一步的疑问, 可以随时重新开启该Issue或者提交一个新的Issue, 谢谢合作.
