### ISSUE TITLE
载入时遇到错误

### ISSUE THREAD

**Issue by aknyzsd** [mnixry/nonebot-plugin-filehost#2]
有可能是我没用nb install造成的，死活找不到包（换源也一样），我就直接下载压缩包解压后丢进bot的src/plugin下直接加载的，有没有办法解决呢qwq
![Screenshot_20231211_232426.jpg](https://github.com/nonebot/plugin-filehost/assets/121467598/f22fde5f-aea6-44fc-bf2f-e792246bd259)

**Comment by he0119** [comment]
请问你当前的 nonebot2 版本是多少？升级一下试试？

**Comment by yanyongyu** [comment]
请升级你的nb2版本

**Comment by aknyzsd** [comment]
问题解决，感谢
