### ISSUE TITLE
如何使用此插件呢

### ISSUE THREAD

**Issue by aknyzsd** [mnixry/nonebot-plugin-filehost#4]
根据文档所述，我应该不需要进行任何操作，在shamrock下发送语音和图片都会遇到以下类似报错，而且确定插件正常加载无报错 
![Screenshot_20240102_133652_com.wujie.connect.jpg](https://github.com/nonebot/plugin-filehost/assets/121467598/adc30bc1-9833-44b7-8657-ff84f836294b)

**Comment by aknyzsd** [comment]
而且图片并不是百分百发不出来，有的时候还能发出来，hook端和nb端在同一内网环境下应该没有网络延迟的问题![Screenshot_20240102_135424_com.wujie.connect.jpg](https://github.com/nonebot/plugin-filehost/assets/121467598/bd6aad1e-6d50-457f-b8fc-e2e38cdd6af0)

**Comment by yanyongyu** [comment]
请提供你发送图片的代码

**Comment by aknyzsd** [comment]
> 请提供你发送图片的代码

咦，图片貌似除了我之外好像都不会复现 奇怪（31分05秒）![Screenshot_20240102_183124_com.wujie.connect.jpg](https://github.com/nonebot/plugin-filehost/assets/121467598/e45996e6-d349-45ca-af21-00e65146b208)
但是语音的报错确实是有的![Screenshot_20240102_184310_com.wujie.connect.jpg](https://github.com/nonebot/plugin-filehost/assets/121467598/6bc306e0-3541-4b65-b6f5-caf13f34d24e)![Screenshot_20240102_184212_com.wujie.connect.jpg](https://github.com/nonebot/plugin-filehost/assets/121467598/6f20a184-c9e7-44a1-8bff-45ca8601a489)

**Comment by yanyongyu** [comment]
```python
from pathlib import Path
from nonebot_plugin_filehost import FileHost

await matcher.finish(MessageSegment.image(await FileHost(Path("/path/to/your/file")).to_url()))
```

**Comment by Redmomn** [comment]
提供一下其他的解决方案
```
with open(file, 'rb') as f:
    data = f.read()
await matcher.finish(MessageSegment.image(file=data))
```
直接读取文件二进制数据，nonebot会自动转为base64发送出去

**Comment by yanyongyu** [comment]
文档已添加使用方法
